// Games & Entertainment — ألعاب وترفيه
module.exports = [
  { id: 3701, text: "ما هي اللعبة الرياضية الإلكترونية الأكثر لاعبين في العالم؟", answer: "League of Legends", letter: "L", category: "ألعاب وترفيه", options: ["League of Legends", "Fortnite", "Minecraft", "Counter-Strike"] },
  { id: 3702, text: "ما هو مقر شركة Nintendo اليابانية؟", answer: "كيوتو", letter: "ك", category: "ألعاب وترفيه", options: ["كيوتو", "طوكيو", "أوساكا", "يوكوهاما"] },
  { id: 3703, text: "ما اسم لعبة البطاقات الأكثر شعبية في العالم العربي؟", answer: "الكونكان", letter: "ك", category: "ألعاب وترفيه", options: ["الكونكان", "الشدة", "الدومينو", "الترمب"] },
  { id: 3704, text: "كم عدد قطع الشطرنج لكل لاعب في بداية اللعبة؟", answer: "16 قطعة", letter: "١", category: "ألعاب وترفيه", options: ["16 قطعة", "12 قطعة", "20 قطعة", "8 قطع"] },
  { id: 3705, text: "ما اسم اللعبة التي تعني 'شعلة' باللغة اليابانية؟", answer: "Nintendo (任天堂) تعني 'دع الحظ يرعى الأمور'", letter: "N", category: "ألعاب وترفيه", options: ["Nintendo", "Atari", "Sega", "Capcom"] },
  { id: 3706, text: "ما هو اسم البطل الرئيسي في لعبة 'Super Mario'؟", answer: "ماريو", letter: "م", category: "ألعاب وترفيه", options: ["ماريو", "لويجي", "يوشي", "واريو"] },
  { id: 3707, text: "في لعبة الشطرنج، ما هي القطعة التي تتحرك فقط بشكل قطري؟", answer: "الفيل (البيدق القطري)", letter: "ف", category: "ألعاب وترفيه", options: ["الفيل (البيدق القطري)", "القلعة", "الحصان", "الوزير"] },
  { id: 3708, text: "ما هو ألعاب الفيديو الأكثر مبيعاً في التاريخ؟", answer: "Minecraft", letter: "M", category: "ألعاب وترفيه", options: ["Minecraft", "GTA 5", "Tetris", "Wii Sports"] },
  { id: 3709, text: "ما اسم البطولة العالمية لألعاب الفيديو الإلكترونية؟", answer: "The International (Dota 2)", letter: "T", category: "ألعاب وترفيه", options: ["The International (Dota 2)", "League of Legends Worlds", "FIFA eWorld Cup", "Fortnite World Cup"] },
  { id: 3710, text: "كم عدد الأحجار في لعبة الدومينو الكاملة؟", answer: "28 حجراً", letter: "٢", category: "ألعاب وترفيه", options: ["28 حجراً", "24 حجراً", "32 حجراً", "36 حجراً"] },
  { id: 3711, text: "ما اسم اللعبة العربية الشعبية التي تستخدم قطعاً ملونة على رقعة؟", answer: "الطاولة (النرد)", letter: "ط", category: "ألعاب وترفيه", options: ["الطاولة (النرد)", "الشطرنج", "الدامة", "الورق"] },
  { id: 3712, text: "ما هي شركة تطوير لعبة 'Call of Duty'؟", answer: "Activision", letter: "A", category: "ألعاب وترفيه", options: ["Activision", "EA Games", "Ubisoft", "Rockstar Games"] },
  { id: 3713, text: "ما هو أول منصة ألعاب تلفزيونية (كونسول) تجارية في العالم؟", answer: "Magnavox Odyssey (1972)", letter: "M", category: "ألعاب وترفيه", options: ["Magnavox Odyssey (1972)", "Atari 2600", "Nintendo NES", "Sega Genesis"] },
  { id: 3714, text: "ما اسم لعبة الورق التي تحتوي على 52 ورقة؟", answer: "البطاقات الفرنسية (Playing Cards)", letter: "ب", category: "ألعاب وترفيه", options: ["البطاقات الفرنسية (Playing Cards)", "أوراق الأونو", "بطاقات المرايا", "الطرنج"] },
  { id: 3715, text: "من هو المصمم الياباني الأسطوري خلف سلسلة 'The Legend of Zelda'؟", answer: "شيغيرو مياموتو", letter: "ش", category: "ألعاب وترفيه", options: ["شيغيرو مياموتو", "هيدو كوجيما", "يوشي كيجيما", "ساتوشي تاجيري"] },
  { id: 3716, text: "ما هو أعلى رقم في لعبة النرد العادية (القرعة)؟", answer: "6", letter: "٦", category: "ألعاب وترفيه", options: ["6", "12", "8", "10"] },
  { id: 3717, text: "ما اسم اللعبة العربية التي تلعب فيها 4 فرق وتدور على رقعة مربعة؟", answer: "الكيرم", letter: "ك", category: "ألعاب وترفيه", options: ["الكيرم", "الدامة", "النرد", "الطاولة"] },
  { id: 3718, text: "في لعبة 'Minecraft'، ما هو اسم المخلوق الأخطر في العالم الافتراضي ليلاً؟", answer: "الزومبي والهيكل العظمي", letter: "ز", category: "ألعاب وترفيه", options: ["الزومبي والهيكل العظمي", "الكريبر", "التنين", "الإنسان الآلي"] },
  { id: 3719, text: "ما اسم المسابقة العالمية لكرة القدم الإلكترونية؟", answer: "بطولة eWorld Cup من EA Sports", letter: "ب", category: "ألعاب وترفيه", options: ["بطولة eWorld Cup من EA Sports", "The International", "ESL Pro League", "Worlds Championship"] },
  { id: 3720, text: "كم عدد اللاعبين في فريق كرة القدم الإلكترونية 5 على 5؟", answer: "خمسة لاعبين", letter: "خ", category: "ألعاب وترفيه", options: ["خمسة لاعبين", "ثلاثة لاعبين", "سبعة لاعبين", "أحد عشر لاعباً"] },
  { id: 3721, text: "ما اسم الجهاز المحمول الذي أطلقته Nintendo عام 1989؟", answer: "Game Boy", letter: "G", category: "ألعاب وترفيه", options: ["Game Boy", "PS Vita", "Sega Game Gear", "Atari Lynx"] },
  { id: 3722, text: "ما هو مفهوم 'eSports'؟", answer: "المسابقات الرياضية الإلكترونية المحترفة", letter: "م", category: "ألعاب وترفيه", options: ["المسابقات الرياضية الإلكترونية المحترفة", "الرياضة على الإنترنت", "الألعاب الإلكترونية التعليمية", "محاكاة الرياضة التقليدية"] },
  { id: 3723, text: "ما اسم أطول سلسلة ألعاب فيديو في التاريخ من حيث عدد الإصدارات؟", answer: "Mario", letter: "M", category: "ألعاب وترفيه", options: ["Mario", "FIFA", "Call of Duty", "Zelda"] },
  { id: 3724, text: "في لعبة الشطرنج، ما القطعة الوحيدة التي تستطيع القفز فوق القطع الأخرى؟", answer: "الحصان (الفارس)", letter: "ح", category: "ألعاب وترفيه", options: ["الحصان (الفارس)", "الفيل", "الوزير", "الملك"] },
  { id: 3725, text: "ما اسم لعبة الورق الشعبية في السعودية التي تحتاج لكشف آخر ورقة؟", answer: "بلوت", letter: "ب", category: "ألعاب وترفيه", options: ["بلوت", "الكونكان", "الزوارق", "الترمب"] },
  { id: 3726, text: "ما هو أول فيلم متحرك ثلاثي الأبعاد لـ Pixar؟", answer: "Toy Story (1995)", letter: "T", category: "ألعاب وترفيه", options: ["Toy Story (1995)", "Finding Nemo", "Monsters Inc", "A Bug's Life"] },
  { id: 3727, text: "ما اسم التقنية التي توفر تجربة الواقع الافتراضي في الألعاب؟", answer: "الواقع الافتراضي (VR)", letter: "و", category: "ألعاب وترفيه", options: ["الواقع الافتراضي (VR)", "الواقع المعزز (AR)", "الشاشة ثلاثية الأبعاد", "البرمجة الهولوغرافية"] },
  { id: 3728, text: "في أي تقنية تتم مشاركة ألعاب الفيديو عبر الإنترنت مع التعليق؟", answer: "البث المباشر (Streaming)", letter: "ب", category: "ألعاب وترفيه", options: ["البث المباشر (Streaming)", "التحميل المسبق", "الواقع الافتراضي", "الشبكة المحلية"] },
  { id: 3729, text: "ما هو منصة المسابقات الإلكترونية السعودية الأبرز؟", answer: "ESLC (بطولات الرياضات الإلكترونية السعودية)", letter: "E", category: "ألعاب وترفيه", options: ["ESLC (بطولات الرياضات الإلكترونية السعودية)", "STC Play", "Gamers8", "G-League"] },
  { id: 3730, text: "ما هو أكبر مهرجان للألعاب الإلكترونية في المملكة العربية السعودية؟", answer: "Gamers8", letter: "G", category: "ألعاب وترفيه", options: ["Gamers8", "GITEX Gaming", "Saudi Gaming", "Riyadh Season Gaming"] },
];
